project:
  type: website

website:
  title: "Qi"
  search:
    location: navbar
    type: overlay
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
      - href: reference.qmd
        text: Reference
      - href: about.qmd
        text: About

format:
  html:
    theme: litera
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto
  